### ISSUE TITLE
Arrays.asList vs new ArrayList(Arrays.asList())

### ISSUE THREAD

**Issue by Jacobvu84** [Jacobvu84/developer-career#2]
### 1. Overview
In this short tutorial, we'll take a look at the differences between Arrays.asList(array) and ArrayList(Arrays.asList(array)).

### 2. Arrays.asList

Let's start with the [Arrays.asList](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Arrays.html#asList(T...)) method.

Using this method, we can convert from an array to a fixed-size List object. **This List is just a wrapper that makes the array available as a list. No data is copied or created.**

Also, we can't modify its length because **adding or removing elements is not allowed.**

However, we can modify single items inside the array. Note that all the **modifications we make to the single items of the List will be reflected in our original array:**

> String[] stringArray = new String[] { "A", "B", "C", "D" };
> List stringList = Arrays.asList(stringArray);

Now, let's see what happens if we modify the first element of _stringList_:

> stringList.set(0, "E");
>  
> assertThat(stringList).containsExactly("E", "B", "C", "D");
> assertThat(stringArray).containsExactly("E", "B", "C", "D");

As we can see, our **original array was modified, too**. Both the list and the array now contain exactly the same elements in the same order.

Let's now try to insert a new element to _stringList_:

> stringList.add("F");

> java.lang.UnsupportedOperationException
> 	at java.base/java.util.AbstractList.add(AbstractList.java:153)
> 	at java.base/java.util.AbstractList.add(AbstractList.java:111)

As we can see, **adding/removing elements to/from the List will throw java.lang.UnsupportedOperationException.**

**Lưu ý những điều quan trọng**
- asList không tạo thêm bất cứ dữ liệu nào, nó chỉ tạo một wrapper cho mảng gốc dưới dạng list nhưng list này không được adding or removing elements.
- Cho phép overwrite the elements có trong stringList và điều này sẽ làm thay đổi cả giá trị ở mảng gốc stringArray

**Comment by Jacobvu84** [comment]
### 3. ArrayList(Arrays.asList(array))
Similar to the Arrays.asList method, we can use ArrayList<>(Arrays.asList(array)) when we need to create a List out of an array.

But, unlike our previous example, this is an independent copy of the array, which means that **modifying the new list won't affect the original array**. Additionally, we have all the capabilities of a regular ArrayList, like adding and removing elements:

**Comment by Jacobvu84** [comment]
### 4. Using List.of()
In contrast to Arrays.asList(), **Java 9** introduced a more convenient method, [List.of()](https://www.baeldung.com/java-init-list-one-line#factory-methods-java-9). This creates instances of unmodifiable List objects:

> String[] array = new String[]{"one", "two", "three"};
> List<String> list = List.of(array);
> assertThat(list).containsExactly("two", "two", "three");

The main difference from Arrays.asList() is that **List.of() returns an _immutable_ list that is a copy of the provided input array**. For this reason, changes to the original array aren't reflected on the returned list:

> String[] array = new String[]{"one", "two", "three"};
> List<String> list = List.of(array);
> array[0] = "thousand";
> assertThat(list.get(0)).isEqualTo("one");

Additionally, we **cannot modify the elements of the list**. If we try to, it will throw UnsupportedOperationException:

> List<String> list = List.of("one", "two", "three");
> assertThrows(UnsupportedOperationException.class, () -> list.set(1, "four"));

We should also note that **List.of() doesn't allow null values as input** and will throw a NullPointerException:

> assertThrows(NullPointerException.class, () -> List.of("one", null, "two"));

Arrays.asList(array) allows null values as input

> List<String> stooges = Arrays.asList("Larry", "Moe", "Curly", null);
